### ISSUE TITLE
Out of storage while unpacking product.img

### ISSUE THREAD

**Issue by RankoR** [kdrag0n/android-webinstall#10]
I'm using Android 13 factory image (oriole-tq1a.221205.011-factory-c9a67c51) for Pixel 6, and getting «Out of storage» while unpacking `product.img`.

My env: MacBook Pro 2020 M1 (16 GB); Vivaldi 5.6.2867.50; About 200 Gigs available on SSD; about 20% of RAM is free.
It's a normal profile, not a guest or incognito.

**Comment by kdrag0n** [comment]
Caused by https://github.com/kdrag0n/fastboot.js/issues/27.
