### ISSUE TITLE
OTA Update through web install

### ISSUE THREAD

**Issue by ehte92** [kdrag0n/android-webinstall#14]
Hi,

I just wanted to know how the update feature works in the webinstall? And from where does it take the update build and what is the mechanism for it. Do you provide the regular factory build for it or you are supposed to provide the ota build. And how is ti configured in the config and the index.json file. Because it isn't very clear to me.

**Comment by kdrag0n** [comment]
It takes factory image packages: https://github.com/kdrag0n/android-webinstall/blob/master/public/releases/index.json
