### ISSUE TITLE
can't download 

### ISSUE THREAD

**Issue by qcscofield** [kdrag0n/android-webinstall#2]
![image](https://user-images.githubusercontent.com/31910172/129304413-71c2a610-4930-4c68-bfe2-bdafb7d9ef64.png)

**Comment by kdrag0n** [comment]
I'm not sure what you mean specifically. The instructions in the error dialog cover most cases; are they not working for you? If so, please send output from the browser console.

**Comment by henkka22** [comment]
Got same error on my fork and console told me about cors and missing header. How I could setup cors proxy for downloading GitHub release?

**Comment by kdrag0n** [comment]
Closing due to lack of response for what is likely a transient issue.
