### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by henkka22** [kdrag0n/android-webinstall#3]
I did fork of this repo to henkka22/android-webinstall but it can't install update. 
![Näyttökuva (6)](https://user-images.githubusercontent.com/33806963/130354206-b9bd89be-4472-4632-9cdb-71538f2225e4.png)

**Comment by kdrag0n** [comment]
It looks like the zip you're providing isn't in the Pixel factory images format, which looks like this:

```
redfin-spb4.210715.011/
redfin-spb4.210715.011/radio-redfin-g7250-00147-210723-b-7576420.img
redfin-spb4.210715.011/flash-base.sh
redfin-spb4.210715.011/flash-all.sh
redfin-spb4.210715.011/image-redfin-spb4.210715.011.zip
redfin-spb4.210715.011/flash-all.bat
redfin-spb4.210715.011/bootloader-redfin-r3-0.4-7508066.img
```

The error message could be better, but that's an issue for [fastboot.js](https://github.com/kdrag0n/fastboot.js).
