### ISSUE TITLE
download flash zip failed

### ISSUE THREAD

**Issue by qcscofield** [kdrag0n/android-webinstall#5]
![image](https://user-images.githubusercontent.com/31910172/139414724-336dc57a-c950-46d5-9381-325dd6b3444a.png)
hello,
How to resolve CORS issue?

**Comment by kdrag0n** [comment]
Only protonaosp.kdrag0n.dev can download from my instance of github-releases-proxy. More info about CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
